/** Code auto-generated by cOde 0.3 **/
#include <R.h> 
 #include <math.h> 

static double parms[7];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 0.00001 

#define IN parms[0] 
 #define R0_kcat_b parms[1] 
 #define R1_kcat_f parms[2] 
 #define R1_kcat_b parms[3] 
 #define R2_kcat_f parms[4] 
 #define y0_0 parms[5] 
 #define y1_0 parms[6] 
#define tmin range[0]
#define tmax range[1]


void toymodel_initmod(void (* odeparms)(int *, double *)) {
	 int N=7;
	 odeparms(&N, parms);
}

void toymodel_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void toymodel_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1*(IN-R0_kcat_b*y[0])-1*(R1_kcat_f*y[0]-R1_kcat_b*y[1]);
 	 ydot[1] = 1*(R1_kcat_f*y[0]-R1_kcat_b*y[1])-1*(R2_kcat_f*y[1]);

}

