/** Code auto-generated by cOde 0.3 **/
#include <R.h> 
 #include <math.h> 

static double parms[21];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 500 
#define nSplines 0 
#define precision 0.00001 

#define IN parms[0] 
 #define R0_kcat_b parms[1] 
 #define R1_kcat_f parms[2] 
 #define R1_kcat_b parms[3] 
 #define R2_kcat_f parms[4] 
 #define y0_0 parms[5] 
 #define y1_0 parms[6] 
 #define y2_0 parms[7] 
 #define y3_0 parms[8] 
 #define y4_0 parms[9] 
 #define y5_0 parms[10] 
 #define y6_0 parms[11] 
 #define y7_0 parms[12] 
 #define y8_0 parms[13] 
 #define y9_0 parms[14] 
 #define y10_0 parms[15] 
 #define y11_0 parms[16] 
 #define y12_0 parms[17] 
 #define y13_0 parms[18] 
 #define y14_0 parms[19] 
 #define y15_0 parms[20] 
#define tmin range[0]
#define tmax range[1]


void toymodel_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=21;
	 odeparms(&N, parms);
}

void toymodel_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void toymodel_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1*(IN-R0_kcat_b*y[0])-1*(R1_kcat_f*y[0]-R1_kcat_b*y[1]);
 	 ydot[1] = 1*(R1_kcat_f*y[0]-R1_kcat_b*y[1])-1*(R2_kcat_f*y[1]);
 	 ydot[2] = (-(R0_kcat_b+R1_kcat_f))*(y[2])+(R1_kcat_b)*(y[3]);
 	 ydot[3] = (R1_kcat_f)*(y[2])+(-(R1_kcat_b+R2_kcat_f))*(y[3]);
 	 ydot[4] = (-(R0_kcat_b+R1_kcat_f))*(y[4])+(R1_kcat_b)*(y[5]);
 	 ydot[5] = (R1_kcat_f)*(y[4])+(-(R1_kcat_b+R2_kcat_f))*(y[5]);
 	 ydot[6] = (-(R0_kcat_b+R1_kcat_f))*(y[6])+(R1_kcat_b)*(y[7])+1;
 	 ydot[7] = (R1_kcat_f)*(y[6])+(-(R1_kcat_b+R2_kcat_f))*(y[7]);
 	 ydot[8] = (-(R0_kcat_b+R1_kcat_f))*(y[8])+(R1_kcat_b)*(y[9])+-y[0];
 	 ydot[9] = (R1_kcat_f)*(y[8])+(-(R1_kcat_b+R2_kcat_f))*(y[9]);
 	 ydot[10] = (-(R0_kcat_b+R1_kcat_f))*(y[10])+(R1_kcat_b)*(y[11])+-y[0];
 	 ydot[11] = (R1_kcat_f)*(y[10])+(-(R1_kcat_b+R2_kcat_f))*(y[11])+y[0];
 	 ydot[12] = (-(R0_kcat_b+R1_kcat_f))*(y[12])+(R1_kcat_b)*(y[13])+y[1];
 	 ydot[13] = (R1_kcat_f)*(y[12])+(-(R1_kcat_b+R2_kcat_f))*(y[13])+-y[1];
 	 ydot[14] = (-(R0_kcat_b+R1_kcat_f))*(y[14])+(R1_kcat_b)*(y[15]);
 	 ydot[15] = (R1_kcat_f)*(y[14])+(-(R1_kcat_b+R2_kcat_f))*(y[15])+-y[1];

}

